# Site settings
title: "Jason Nasr E-Portfolio"
description: "Welcome to my ePortfolio! This space showcases my enhanced software engineering projects, refined through detailed code reviews and thoughtful improvements. Each project reflects my growth in writing clean, modular, and well-documented                 code, with a focus on structure, functionality, and user experience. Dive in to explore the updates I've made and how each enhancement demonstrates my commitment to writing professional, maintainable, and       efficient software."

# Jekyll settingg
theme: jekyll-theme-slate
